[2025-07-15T04:04:05.243+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-15T04:04:05.271+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflights_etl_pipeline.load scheduled__2025-07-15T04:02:00+00:00 [queued]>
[2025-07-15T04:04:05.281+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflights_etl_pipeline.load scheduled__2025-07-15T04:02:00+00:00 [queued]>
[2025-07-15T04:04:05.314+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-15T04:04:05.329+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2025-07-15 04:02:00+00:00
[2025-07-15T04:04:05.338+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2416) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-15T04:04:05.338+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'airflights_etl_pipeline', 'load', 'scheduled__2025-07-15T04:02:00+00:00', '--job-id', '1826', '--raw', '--subdir', 'DAGS_FOLDER/airflight_pipeline.py', '--cfg-path', '/tmp/tmpeu70j3bl']
[2025-07-15T04:04:05.339+0000] {standard_task_runner.py:63} INFO - Started process 2418 to run task
[2025-07-15T04:04:05.340+0000] {standard_task_runner.py:91} INFO - Job 1826: Subtask load
[2025-07-15T04:04:05.353+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-15T04:04:05.384+0000] {task_command.py:426} INFO - Running <TaskInstance: airflights_etl_pipeline.load scheduled__2025-07-15T04:02:00+00:00 [running]> on host 5a1293588d06
[2025-07-15T04:04:05.666+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='airflights_etl_pipeline' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T04:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-15T04:02:00+00:00'
[2025-07-15T04:04:05.667+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-15T04:04:05.678+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-15T04:04:05.679+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: load_etl() missing 2 required positional arguments: 'summary_file' and 'full_file'
[2025-07-15T04:04:05.688+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=airflights_etl_pipeline, task_id=load, run_id=scheduled__2025-07-15T04:02:00+00:00, execution_date=20250715T040200, start_date=20250715T040405, end_date=20250715T040405
[2025-07-15T04:04:05.704+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1826 for task load (load_etl() missing 2 required positional arguments: 'summary_file' and 'full_file'; 2418)
[2025-07-15T04:04:05.754+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-15T04:04:05.772+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-15T04:04:05.831+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
