[2025-07-13T16:12:32.944+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: airflights_etl_pipeline.extract scheduled__2025-07-13T15:50:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
