[2025-07-15T06:32:01.475+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: airflights_etl_pipeline.extract_task.extract4 scheduled__2025-07-15T06:30:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
