[2025-07-15T06:43:07.175+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: airflights_etl_pipeline.load scheduled__2025-07-15T06:40:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
